name: myrik_intern_task
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^8.0.3
  dio: ^5.3.2
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  geolocator: ^11.0.0
  gif_view: ^0.4.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  open_store: ^0.5.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  platform_info: ^4.0.2
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3
  velocity_x: ^4.1.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.1.0
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
